FROM atoml/android-nodejs AS cordova

ENV CORDOVA_VERSION 8.0.0

WORKDIR "/root"

RUN npm i -g --unsafe-perm cordova@${CORDOVA_VERSION}

FROM cordova AS ionic

ENV IONIC_VERSION 4.5.0

RUN apt-get update && apt-get install -y git bzip2 openssh-client && \
    npm i -g --unsafe-perm ionic@${IONIC_VERSION} && \
    ionic --no-interactive config set -g daemon.updates false && \
    rm -rf /var/lib/apt/lists/* && apt-get clean

///////////////////////////////////////////////////////////////////////////

