#源镜像
FROM debian:latest
#作者
MAINTAINER marmotcai "marmotcai@163.com"

##########################################################################################################
## IPFS-CLUSTER-SERVICE

ENV IPFS_GOIPFS_CLUSTER_URL https://dist.ipfs.io/ipfs-cluster-service/v0.4.0/ipfs-cluster-service_v0.4.0_linux-amd64.tar.gz

ENV IPFS_DIR .
ENV IPFS_GOIPFS_CLUSTER ipfs-cluster-service

RUN mkdir IPFS_GOIPFS_CLUSTER
WORKDIR IPFS_GOIPFS_CLUSTER

RUN echo $IPFS_GOIPFS_CLUSTER

#本地
COPY $IPFS_DIR/$IPFS_GOIPFS_CLUSTER.tar.gz .
#远程
#RUN apt update && apt install -y wget
#RUN wget -qO $IPFS_DIR/$IPFS_GOIPFS_CLUSTER.tar.gz $IPFS_GOIPFS_CLUSTER_URL

RUN tar zxf $IPFS_GOIPFS_CLUSTER.tar.gz
RUN cd $IPFS_GOIPFS_CLUSTER && sh install.sh

##########################################################################################################

##暴露端口
EXPOSE 880 8080

#最终运行docker的命令
ENTRYPOINT ["ipfs", "daemon", "--offline"]

##########################################################################################################

