#源镜像
FROM debian:latest
#作者
MAINTAINER marmotcai "marmotcai@163.com"

##########################################################################################################
## IPFS

ENV IPFS_URL https://github.com/ipfs/go-ipfs/releases/download/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz

ENV IPFS_DIR .
ENV IPFS_GOIPFS go-ipfs

RUN mkdir IPFS_DIR
WORKDIR IPFS_DIR

RUN echo $IPFS_DIR

#本地
COPY $IPFS_DIR/$IPFS_GOIPFS.tar.gz .
#远程
#RUN apt update && apt install -y wget
#RUN wget -qO $IPFS_DIR/$IPFS_GOIPFS.tar.gz $IPFS_URL

RUN tar zxf $IPFS_GOIPFS.tar.gz
RUN cd $IPFS_GOIPFS && sh install.sh

RUN ipfs init

##########################################################################################################

##暴露端口
EXPOSE 880 8080

#最终运行docker的命令
ENTRYPOINT ["ipfs", "daemon", "--offline"]

##########################################################################################################

